# Generated by Django 4.1.2 on 2022-11-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0002_amigos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigos',
            old_name='años_de_amistad',
            new_name='anios_de_amistad',
        ),
    ]
