# Generated by Django 4.1.2 on 2022-11-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerApp', '0003_rename_años_de_amistad_amigos_anios_de_amistad'),
    ]

    operations = [
        migrations.CreateModel(
            name='colegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_de_telefono', models.IntegerField()),
            ],
        ),
    ]
